name: example

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

env:
  DEPLOY_DIR: examples/vite/dist
  DEPLOY_FILTER: example-swetrix-vue-vite

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        env:
          VITE_SWETRIX_PROJECT_ID: ${{ secrets.VITE_SWETRIX_PROJECT_ID }}
        uses: ghacts/static-site@main
        with:
          node-version: 18
          skip-lint: true
          skip-test: true
          build-script: 'build:example'
          output-dir: ${{ env.DEPLOY_DIR }}

      - name: Deploy preview
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        uses: ghacts/manual-deploy-to-netlify@main
        with:
          auth-token: ${{ env.NETLIFY_AUTH_TOKEN }}
          site: ${{ env.NETLIFY_SITE_ID }}
          filter: ${{ env.DEPLOY_FILTER }}
